<!--
FILE: 			: <?php echo basename(__FILE__, $_SERVER['PHP_SELF'])."\n"; ?>
TITLE           : AveNest Listings
AUTHORS         : Smit Patel, Mike Cusson, Roshan Persaud
LAST MODIFIED   : NOV 11, 2019
DESCRIPTION     : Listing City Select
-->
<?php
$title  = "Listing City Select";
$file   = "listing-search.php";
$date   = "NOV 11, 2019";
$banner = "Listing City Select";
$desc   = "Listing City Select Page used to select a city";
require("./header.php");
?>
    <div class="text-center flex flex-wrap flex-col py-4 content-center container mx-auto justify-center">
        <p class="text-2xl text-primary-500 w-auto lg:w-1/3 py-2 px-3 font-headline font-semibold underline">
            Select A City
        </p>
    </div>
    <form method="post" action="/listing-search.php" class="w-full flex flex-wrap justify-center items-center py-10">
        <!-- Image Map Generated by http://www.image-map.net/ -->
        <img src="./images/durham_region.jpg" usemap="#image-map">
        <map name="image-map">
            <area target="_self" alt="scugog" title="scugog" href="./listing-search.php?city=256" coords="560,115,217,1" shape="rect">
            <area target="_self" alt="pickering" title="pickering" href="./listing-search.php?city=16" coords="40,331,43,117,215,116,215,228,137,230,140,363,59,366" shape="poly">
            <area target="_self" alt="ajax" title="ajax" href="./listing-search.php?city=1" coords="212,364,137,231" shape="rect">
            <area target="_self" alt="whitby" title="whitby" href="./listing-search.php?city=64" coords="215,117,300,365" shape="rect">
            <area target="_self" alt="oshawa" title="oshawa" href="./listing-search.php?city=8" coords="304,119,388,371" shape="rect">
            <area target="_self" alt="clarington" title="clarington" href="./listing-search.php?city=128" coords="391,116,632,391" shape="rect">
        </map>
    </form>
<?php
require("./footer.php");
?>